---
# This task decides the active profile and then initializes Flexible Profiles.

- name: Set Flexible Profiles paths as facts
  ansible.builtin.set_fact:
    fp_defaults_path: "{{ role_path }}/vars/fp/fp_defaults"
    fp_instant_expressions_path: "{{ role_path }}/vars/fp/fp_instant_expressions"
    fp_deferred_expressions_path: "{{ role_path }}/vars/fp/fp_deferred_expressions"

# This task initializes Flexible Profiles for this role.
- name: Load Flexible Profiles for myapp
  ansible.builtin.include_role:
    name: FlexibleProfiles
  vars:
    # 1. Provide the name of this role for namespacing internal FP variables.
    fp_consumer_role_name: "myapp"

    # 2. (Optional) Set to true to prefix all realized variables with the role name.
    fp_export_with_consumer_role_prefix: true

    # 3. Determine the active profile directly here based on OS facts.
    fp_active_profile: >-
      {{
        'RedHat-' + ansible_distribution_major_version if ansible_os_family == 'RedHat'
        else 'Windows-2022' if ansible_os_family == 'Windows'
        else 'unknown'
      }}

    # 4. Provide the list of valid profiles for this role.
    fp_profile_names:
      - "RedHat-9"
      - "Windows-2022"
