---
# Import all profile-specific handlers.
- name: MYAPP04 | handlers | main.yml | Import PROD handlers
  ansible.builtin.import_tasks: PROD.yml
- name: MYAPP04 | handlers | main.yml | Import UAT handlers
  ansible.builtin.import_tasks: UAT.yml
