---
# This task decides the active profile and then initializes Flexible Profiles.

- name: MYAPP03 | Capture caller role_path
  ansible.builtin.set_fact:
    myapp03_role_path: "{{ role_path }}"

# This task initializes Flexible Profiles for this role.
- name: MYAPP03 | init_fp.yml | Load Flexible Profiles for myapp03
  ansible.builtin.include_role:
    name: fp
  vars:
    fp_defaults_path: "{{ myapp03_role_path }}/vars/fp/fp_defaults"
    fp_instant_expressions_path: "{{ myapp03_role_path }}/vars/fp/fp_instant_expressions"
    # The deferred expressions path is set to "skip" to disable this layer
    fp_deferred_expressions_path: "skip"

    # 1. Provide the name of this role for namespacing internal FP variables.
    fp_consumer_role_name: "myapp03"

    # 2. Set to true to prefix all realized variables with the role name.
    fp_export_with_consumer_role_prefix: true

    # 3. Determine the active profile based on the 'non_prod' boolean.
    fp_active_profile: "{{ 'WindowsDev' if non_prod | bool else 'WindowsProd' }}"

    # 4. Provide the list of valid profiles for this role.
    fp_profile_names:
      - "WindowsProd"
      - "WindowsDev"
